version: '3.9'
services:
  postgresql:
    container_name: sistema-omet-postgresql
    image: 'postgres:14.7-alpine'
    ports:
      - '5432:5432'
    env_file: ./env_files/postgresql/.env
    volumes:
      - 'dev-db-data:/var/lib/postgresql/data'
  api:
    container_name: sistema-omet-api
    build:
      context: ./api
      args:
        - DEV=true
    ports:
      - '8001:8001'
    env_file: ./env_files/api/.env
    entrypoint: sh -c "sh ./entrypoint.sh"
    volumes:
      - './api:/api'
      - dev-static-data:/vol/web
    depends_on:
      - rabbitmq
      - postgresql
  rabbitmq:
    container_name: sistema-omet-rabbitmq
    image: 'rabbitmq:3.8.9-management-alpine'
    ports:
      - '5672:5672'
    env_file: ./env_files/rabbitmq/.env
  web:
    container_name: sistema-omet-web
    build:
      context: ./web
      args:
        - DEV=true
    ports:
      - '3001:3001'
    command: sh -c "npm install --dev --silent && npm start"
    stdin_open: true
    volumes:
      - './web:/web'
    depends_on:
      - api
  mongodb:
    image: mongo
    container_name: sistema-omet-mongo
    ports:
      - '27017:27017'
    env_file: ./env_files/mongodb/.env
    volumes:
      - dev-mongo-data:/data/db
volumes:
  dev-db-data:
  dev-static-data:
  dev-mongo-data:
