# Generated by Django 3.2.18 on 2023-04-22 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_maintenance_maintainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintainer',
            name='id',
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
