# Generated by Django 3.2.18 on 2023-05-03 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_resetpasswordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='maintainers',
            field=models.ManyToManyField(through='core.Maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='maintenance',
            unique_together={('user', 'project')},
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='maintainer',
        ),
        migrations.DeleteModel(
            name='Maintainer',
        ),
    ]
