# Generated by Django 3.2.18 on 2023-05-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_modelfield_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datefieldconfig',
            name='date_field_type',
        ),
        migrations.RemoveField(
            model_name='datefieldconfig',
            name='model_field',
        ),
        migrations.RemoveField(
            model_name='filefieldconfig',
            name='content_types',
        ),
        migrations.RemoveField(
            model_name='filefieldconfig',
            name='model_field',
        ),
        migrations.RemoveField(
            model_name='floatfieldconfig',
            name='model_field',
        ),
        migrations.RemoveField(
            model_name='foreignkeyfieldconfig',
            name='input_type',
        ),
        migrations.RemoveField(
            model_name='foreignkeyfieldconfig',
            name='model_field',
        ),
        migrations.RemoveField(
            model_name='foreignkeyfieldconfig',
            name='model_field_relation',
        ),
        migrations.RemoveField(
            model_name='integerfieldconfig',
            name='model_field',
        ),
        migrations.AddField(
            model_name='datatype',
            name='config_fields',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='modelfield',
            name='config_fields',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='CharFieldConfig',
        ),
        migrations.DeleteModel(
            name='ContentTypes',
        ),
        migrations.DeleteModel(
            name='DateFieldConfig',
        ),
        migrations.DeleteModel(
            name='FileFieldConfig',
        ),
        migrations.DeleteModel(
            name='FloatFieldConfig',
        ),
        migrations.DeleteModel(
            name='ForeignKeyFieldConfig',
        ),
        migrations.DeleteModel(
            name='IntegerFieldConfig',
        ),
    ]
