# Generated by Django 3.2.18 on 2023-05-12 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230511_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='input_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.inputtype'),
        ),
    ]
