# Generated by Django 3.2.18 on 2023-05-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230511_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateFieldType',
        ),
    ]
