# Generated by Django 3.2.18 on 2023-05-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
