# Generated by Django 3.2.18 on 2023-05-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='is_static',
        ),
    ]
