# Generated by Django 3.2.18 on 2023-05-15 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignKeyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model_field_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_field_origin', to='core.modelfield')),
                ('model_field_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelfield')),
            ],
            options={
                'verbose_name': 'Foreign Key Relation',
                'verbose_name_plural': 'Foreign Key Relations',
                'db_table': 'ForeignKeyRelation',
                'unique_together': {('model_field_origin', 'model_field_relation')},
            },
        ),
    ]
