# Generated by Django 3.2.18 on 2023-05-15 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_foreignkeyrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('value_type', models.CharField(choices=[('string', 'str'), ('integer', 'int'), ('float', 'float'), ('boolean', 'bool')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datatype')),
            ],
            options={
                'verbose_name': 'Config Field',
                'verbose_name_plural': 'Config Fields',
                'db_table': 'ConfigFields',
                'unique_together': {('name', 'data_type')},
            },
        ),
        migrations.CreateModel(
            name='ConfigValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.configfields')),
            ],
            options={
                'verbose_name': 'Config Value',
                'verbose_name_plural': 'Config Values',
                'db_table': 'ConfigValues',
                'unique_together': {('config_field', 'value')},
            },
        ),
    ]
