# Generated by Django 3.2.18 on 2023-05-15 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_configfields_configvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='configvalues',
            name='model_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.modelfield'),
            preserve_default=False,
        ),
    ]
