# Generated by Django 3.2.18 on 2023-05-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_datatype_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='input_type',
            field=models.CharField(choices=[('String', 'char'), ('Integer', 'int'), ('Float', 'float'), ('Boolean', 'bool'), ('Checkbox', 'checkbox'), ('Select', 'select'), ('Radio', 'radio')], max_length=255),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='datatype',
            unique_together={('name', 'input_type')},
        ),
    ]
