# Generated by Django 3.2.19 on 2023-05-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20230515_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfields',
            name='value_type',
            field=models.CharField(choices=[('String', 'str'), ('Integer', 'int'), ('Float', 'float'), ('Boolean', 'bool')], max_length=255),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='input_type',
            field=models.CharField(choices=[('String', 'text'), ('Number', 'number'), ('Checkbox', 'checkbox'), ('Select', 'select'), ('Radio', 'radio')], max_length=255),
        ),
        migrations.DeleteModel(
            name='ForeignKeyRelation',
        ),
    ]
