# Generated by Django 3.2.19 on 2023-05-17 04:36

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20230515_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInsertionLogs',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name_registered', models.TextField()),
                ('first_last_name_registered', models.TextField()),
                ('second_last_name_registered', models.TextField()),
                ('email_registered', models.TextField()),
                ('phone_registered', models.TextField()),
                ('is_superuser', models.BooleanField()),
                ('inserted_by', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_insertion_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='configfields',
            name='value_type',
            field=models.CharField(choices=[('String', 'str'), ('Integer', 'int'), ('Float', 'float'), ('Boolean', 'bool')], max_length=255),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='input_type',
            field=models.CharField(choices=[('String', 'text'), ('Number', 'number'), ('Checkbox', 'checkbox'), ('Select', 'select'), ('Radio', 'radio')], max_length=255),
        ),
    ]
