# Generated by Django 3.2.20 on 2023-07-23 20:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230522_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Validator',
                'verbose_name_plural': 'Validators',
                'db_table': 'Validator',
            },
        ),
        migrations.CreateModel(
            name='ValidatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Validator Value',
                'verbose_name_plural': 'Validator Values',
                'db_table': 'ValidatorValue',
            },
        ),
        migrations.AlterUniqueTogether(
            name='configvalues',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='configvalues',
            name='config_field',
        ),
        migrations.RemoveField(
            model_name='configvalues',
            name='model_field',
        ),
        migrations.AlterField(
            model_name='modelfield',
            name='order',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='datatype',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='ConfigFields',
        ),
        migrations.DeleteModel(
            name='ConfigValues',
        ),
        migrations.AddField(
            model_name='validatorvalue',
            name='model_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelfield'),
        ),
        migrations.AddField(
            model_name='validatorvalue',
            name='validator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.validator'),
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='input_type',
        ),
        migrations.RemoveField(
            model_name='datatype',
            name='is_active',
        ),
        migrations.AddField(
            model_name='datatype',
            name='validators',
            field=models.ManyToManyField(blank=True, to='core.Validator'),
        ),
        migrations.AlterUniqueTogether(
            name='validatorvalue',
            unique_together={('validator', 'model_field')},
        ),
    ]
