# Generated by Django 3.2.19 on 2023-05-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230516_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinsertionlogs',
            options={'managed': False, 'verbose_name': 'User Insertion Log', 'verbose_name_plural': 'User Insertion Logs'},
        ),
    ]
