# Generated by Django 3.2.20 on 2023-07-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20230723_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatype',
            name='created_at',
        ),
    ]
