# Generated by Django 3.2.19 on 2023-05-17 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_userinsertionlogs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinsertionlogs',
            options={'verbose_name': 'User Insertion Log', 'verbose_name_plural': 'User Insertion Logs'},
        ),
    ]
