# Generated by Django 3.2.19 on 2023-05-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_userinsertionlogs_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinsertionlogs',
            old_name='_id',
            new_name='id',
        ),
        migrations.AlterModelTable(
            name='userinsertionlogs',
            table='UserInsertionLogs',
        ),
    ]
