# Generated by Django 3.2.20 on 2023-07-24 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_datatype_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfield',
            name='is_required',
        ),
    ]
