# Generated by Django 3.2.20 on 2023-07-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_modelfield_is_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_last_name',
            field=models.CharField(default='last_name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='second_last_name',
            field=models.CharField(default='last_name', max_length=255),
            preserve_default=False,
        ),
    ]
