# Generated by Django 3.2.19 on 2023-05-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20230517_0011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInsertionLogs',
        ),
    ]
