# Generated by Django 3.2.20 on 2023-07-26 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20230724_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'verbose_name': 'Project App',
                'verbose_name_plural': 'Project Apps',
                'db_table': 'project_app',
                'ordering': ['project'],
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='project_app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.projectapp'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='projectmodel',
            unique_together={('name', 'project_app')},
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='project',
        ),
    ]
