# Generated by Django 3.2.19 on 2023-05-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_userinsertionlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInsertionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_registered', models.CharField(max_length=50)),
                ('first_last_name_registered', models.CharField(max_length=50)),
                ('second_last_name_registered', models.CharField(max_length=50)),
                ('email_registered', models.EmailField(max_length=255)),
                ('phone_registered', models.CharField(max_length=20)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Insertion Log',
                'verbose_name_plural': 'User Insertion Logs',
                'db_table': 'UserInsertionLogs',
            },
        ),
    ]
