# Generated by Django 3.2.19 on 2023-05-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_userinsertionlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinsertionlogs',
            name='is_superuser',
        ),
    ]
