# Generated by Django 3.2.20 on 2023-09-19 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20230918_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfield',
            name='model_field_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modelfield'),
        ),
    ]
