# Generated by Django 3.2.19 on 2023-05-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_userinsertionlogs_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsertionlogs',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ForeignKeyRelation',
        ),
    ]
