# Generated by Django 3.2.20 on 2023-09-19 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_modelfield_model_field_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfield',
            name='model_field_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modelfield'),
        ),
    ]
