# Generated by Django 3.2.22 on 2023-11-10 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20231017_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='maintainers',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
