# Generated by Django 3.2.22 on 2023-11-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20231110_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfield',
            name='model_field_relation',
        ),
    ]
