# Generated by Django 3.2.22 on 2023-11-15 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_modelfield_model_field_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignKeyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_field_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_field_origin', to='core.appmodel', unique=True)),
                ('model_field_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_field_related', to='core.appmodel')),
            ],
            options={
                'verbose_name': 'Foreign Key Relation',
                'verbose_name_plural': 'Foreign Key Relations',
                'db_table': 'ForeignKeyRelation',
                'unique_together': {('model_field_origin', 'model_field_related')},
            },
        ),
    ]
