# Generated by Django 3.2.22 on 2023-11-15 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_foreignkeyrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignkeyrelation',
            name='model_field_origin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_field_origin', to='core.appmodel'),
        ),
    ]
