# Generated by Django 3.2.22 on 2023-11-15 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_foreignkeyrelation_model_field_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignkeyrelation',
            name='model_field_origin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_field_origin', to='core.modelfield'),
        ),
        migrations.AlterField(
            model_name='foreignkeyrelation',
            name='model_field_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_field_related', to='core.modelfield'),
        ),
    ]
