# Generated by Django 3.2.22 on 2023-11-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20231114_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfield',
            name='data_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.datatype'),
            preserve_default=False,
        ),
    ]
